# Generated by Django 5.0 on 2024-01-15 17:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_circuito', models.CharField(max_length=20)),
                ('nombre_circuito', models.CharField(max_length=100)),
                ('numero_circuito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('km', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangopersona', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rango',
                'verbose_name_plural': 'Rangos',
            },
        ),
        migrations.CreateModel(
            name='Subcircuito',
            fields=[
                ('cod_subcircuito', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre_subcircuito', models.CharField(max_length=100)),
                ('numero_subcircuito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subcircuito',
                'verbose_name_plural': 'Subcircuitos',
            },
        ),
        migrations.CreateModel(
            name='Tipomantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo mantenimiento',
                'verbose_name_plural': 'Tipo de mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Tipovehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovehiculo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(max_length=20)),
                ('detalle', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('id_circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.circuito')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncia',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_distrito', models.CharField(max_length=20)),
                ('nombre_distrito', models.CharField(max_length=100)),
                ('numero_distrito', models.CharField(max_length=100)),
                ('id_circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.circuito')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.distrito')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Entradamtto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentrada', models.ImageField(upload_to='docentradamancar/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.mantenimiento')),
            ],
            options={
                'verbose_name': 'Entrada mantenimiento',
                'verbose_name_plural': 'Entrada mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='OrdendeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('ruta', models.CharField(max_length=1000)),
                ('km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.dependencia')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='EntradaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentradaorden', models.ImageField(upload_to='docentradaorden/')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.ordendetrabajo')),
            ],
            options={
                'verbose_name': 'Entrada Orden',
                'verbose_name_plural': 'Entradas Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now)),
                ('tipo_sangre', models.CharField(max_length=10)),
                ('ciudad_nacimiento', models.CharField(max_length=25)),
                ('numero_celular', models.CharField(max_length=10)),
                ('codigoempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.dependencia')),
                ('id_rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.rango')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='agente1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordendetrabajo_agente1', to='appflotavehicular.persona'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='agente2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordendetrabajo_agente2', to='appflotavehicular.persona'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='agente3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordendetrabajo_agente3', to='appflotavehicular.persona'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.persona'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.persona'),
        ),
        migrations.CreateModel(
            name='Salidamtto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docsalida', models.ImageField(upload_to='docsalidamancar/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.mantenimiento')),
            ],
            options={
                'verbose_name': 'Salida mantenimiento',
                'verbose_name_plural': 'Salida mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='SalidaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docsalidaorden', models.ImageField(upload_to='docsalidaorden/')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.ordendetrabajo')),
            ],
            options={
                'verbose_name': 'Salida Orden',
                'verbose_name_plural': 'Salidas Ordenes',
            },
        ),
        migrations.AddField(
            model_name='circuito',
            name='id_subcircuito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.subcircuito'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipodemantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.tipomantenimiento'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('chasis', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('cilindraje', models.FloatField()),
                ('capacidad_carga', models.FloatField()),
                ('capacidad_pasajeros', models.IntegerField()),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('tipovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.vehiculo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.vehiculo'),
        ),
    ]
