# Generated by Django 5.0 on 2024-01-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='id_subcircuito',
            field=models.ForeignKey(default='11D01C 01S01', on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.subcircuito'),
            preserve_default=False,
        ),
    ]
