# Generated by Django 5.0 on 2023-12-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
