# Generated by Django 4.2.8 on 2024-02-06 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_galones', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField()),
                ('km_actual', models.CharField(max_length=20)),
                ('nombre_servpolicial', models.CharField(max_length=100)),
                ('nombre_gasolinera', models.CharField(max_length=100)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.dependencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.persona')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.vehiculo')),
            ],
            options={
                'verbose_name': 'Combustible',
                'verbose_name_plural': 'Combustibles',
            },
        ),
    ]
