# Generated by Django 5.0 on 2023-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0002_alter_tipovehiculo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipomantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo mantenimiento',
                'verbose_name_plural': 'Tipo de mantenimientos',
            },
        ),
    ]
