# Generated by Django 5.0 on 2023-12-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0006_persona_codigoempleado_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='contraseña',
        ),
    ]
