# Generated by Django 5.0 on 2023-12-25 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0007_remove_persona_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 21, 41, 45, 895225)),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='km',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 21, 41, 45, 893224)),
        ),
    ]
