# Generated by Django 5.0 on 2023-12-25 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0008_alter_mantenimiento_fecha_alter_mantenimiento_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 21, 53, 30, 925998)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 21, 53, 30, 923994)),
        ),
    ]
