# Generated by Django 5.0 on 2023-12-27 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0009_mantenimiento_estado_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('cod_circuito', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_circuito', models.CharField(max_length=100)),
                ('numero_circuito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('cod_distrito', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_distrito', models.CharField(max_length=100)),
                ('numero_distrito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Subcircuito',
            fields=[
                ('cod_subcircuito', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_subcircuito', models.CharField(max_length=100)),
                ('numero_subcircuito', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subcircuito',
                'verbose_name_plural': 'Subcircuitos',
            },
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 16, 36, 45, 529747)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 27, 16, 36, 45, 527730)),
        ),
    ]
