# Generated by Django 5.0 on 2023-12-28 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0012_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 16, 31, 18, 708206)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 16, 31, 18, 706207)),
        ),
    ]
