# Generated by Django 5.0 on 2023-12-29 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0013_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 17, 8, 32, 645311)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 17, 8, 32, 643312)),
        ),
    ]
