# Generated by Django 5.0 on 2023-12-29 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0014_vehiculo_estado_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 17, 9, 30, 750975)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 17, 9, 30, 748976)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
