# Generated by Django 5.0 on 2023-12-30 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0015_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contraseña_firma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmasempleados/'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 17, 42, 14, 465660)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 17, 42, 14, 463661)),
        ),
    ]
