# Generated by Django 5.0 on 2023-12-30 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0016_persona_contraseña_firma_persona_firma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='contraseña_firma',
            new_name='contrasenia_firma',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 17, 51, 46, 535763)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 17, 51, 46, 533764)),
        ),
    ]
