# Generated by Django 5.0 on 2023-12-31 01:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0017_rename_contraseña_firma_persona_contrasenia_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 20, 6, 23, 72528)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 30, 20, 6, 23, 70530)),
        ),
        migrations.CreateModel(
            name='Salidamtto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docsalida', models.ImageField(upload_to='docsalidamancar/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.mantenimiento')),
            ],
            options={
                'verbose_name': 'Salida mantenimiento',
                'verbose_name_plural': 'Salida mantenimientos',
            },
        ),
    ]
