# Generated by Django 5.0 on 2023-12-31 21:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0018_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 31, 16, 13, 36, 702072)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 12, 31, 16, 13, 36, 700073)),
        ),
        migrations.CreateModel(
            name='Entradamtto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentrada', models.ImageField(upload_to='docentradamancar/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.mantenimiento')),
            ],
            options={
                'verbose_name': 'Entrada mantenimiento',
                'verbose_name_plural': 'Entrada mantenimientos',
            },
        ),
    ]
