# Generated by Django 5.0 on 2024-01-02 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0020_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Dependencia', 'verbose_name_plural': 'Dependencias'},
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 32, 39, 306336)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 32, 39, 304337)),
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
    ]
