# Generated by Django 5.0 on 2024-01-02 21:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0021_alter_distrito_options_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AddField(
            model_name='circuito',
            name='id_subcircuito',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.subcircuito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 33, 5, 349220)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 33, 5, 345219)),
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('parroquia', models.CharField(max_length=50)),
                ('id_circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.circuito')),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.distrito')),
                ('id_subcircuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appflotavehicular.subcircuito')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
    ]
