# Generated by Django 5.0 on 2024-01-02 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0022_alter_distrito_options_circuito_id_subcircuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 33, 26, 756800)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 33, 26, 754797)),
        ),
    ]
