# Generated by Django 5.0 on 2024-01-03 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0023_alter_mantenimiento_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='cod_circuito',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='identificacion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cod_distrito',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 20, 17, 30, 855113)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 20, 17, 30, 853114)),
        ),
        migrations.AlterField(
            model_name='subcircuito',
            name='cod_subcircuito',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
