# Generated by Django 5.0 on 2024-01-03 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflotavehicular', '0024_alter_circuito_cod_circuito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 20, 17, 41, 47074)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 20, 17, 41, 45076)),
        ),
    ]
